### ISSUE TITLE
Contador de caracteres

### ISSUE THREAD

**Issue by brunohpmarques** [netoeuc/elesson#4]
Na página de cadastro de questões, deveria ter um contador de caracteres para não perder tempo cadastrando questões longas e no final não cadastrar.

Página: http://localhost:9000/panel/teacher/questions

**Comment by ghost** [comment]
Contador de caracteres implementado, tentando implementar também um forma de limitar o professor escrever no máximo 254 caracteres

**Comment by brunohpmarques** [comment]
Por limitação da biblioteca utilizada, não foi possível limitar a quantidade de caracteres no campo, porém, foi desenvolvido uma maneira de destacar (alterando a cor preta para vermelha) que a quantidade de caracteres digitadas ultrapassou a quantidade permitida.
